### ISSUE TITLE
Compiling against libwiretap-dev 1.12 fails

### ISSUE THREAD

**Issue by CyberTaoFlow** [CIRCL/pcapdj#2]
Greetings! First thank you for this awesome tool which is filling a need for myself very elegantly.

I have found that pcapdj will not compile on debian systems with newer libwiretap headers.  If I install the headers associated with libwiretap3 
(version 1.10 from http://lmde-mirror.gwendallebihan.net/latest//pool/main/w/wireshark/libwiretap-dev_1.10.3-1~bpo70+1_amd64.deb )

And add '-I /usr/include/wireshark' to the Makefile I am then able to compile.

The version currently being distributed with debian is 
ii  libwiretap-dev                       1.12.1+g01b65bf-4+deb8u9     amd64        network packet capture library -- development files

When I try to make against that I have the following result;

make
gcc -Wall -c pcapdj.c `pkg-config --cflags glib-2.0` -I /usr/include/wireshark/wiretap `pkg-config --libs glib-2.0` -I /usr/local/include/hiredis -ggdb
In file included from pcapdj.c:29:0:
/usr/include/wireshark/wiretap/wtap.h:30:27: fatal error: wsutil/buffer.h: No such file or directory
 #include <wsutil/buffer.h>
                           ^
compilation terminated.
Makefile:4: recipe for target 'pcapdj.o' failed
make: *** [pcapdj.o] Error 1

If  I extend the include paths to include wsutil and wireshark header directories i get

gcc -Wall -c pcapdj.c `pkg-config --cflags glib-2.0` -I /usr/include/wireshark/wiretap `pkg-config --libs glib-2.0` -I /usr/local/include/hiredis -ggdb -I /usr/include/wireshark/wsutil -I /usr/include/wireshark

pcapdj.c: In function ‘process_file’:
pcapdj.c:430:41: warning: passing argument 2 of ‘wtap_open_offline’ makes integer from pointer without a cast
     wth = wtap_open_offline ( filename, (int*)&err, (char**)&errinfo, FALSE);
                                         ^
In file included from pcapdj.c:29:0:
/usr/include/wireshark/wiretap/wtap.h:1377:14: note: expected ‘unsigned int’ but argument is of type ‘int *’
 struct wtap* wtap_open_offline(const char *filename, unsigned int type, int *err,
              ^
pcapdj.c:430:53: warning: passing argument 3 of ‘wtap_open_offline’ from incompatible pointer type
     wth = wtap_open_offline ( filename, (int*)&err, (char**)&errinfo, FALSE);
                                                     ^
In file included from pcapdj.c:29:0:
/usr/include/wireshark/wiretap/wtap.h:1377:14: note: expected ‘int *’ but argument is of type ‘char **’
 struct wtap* wtap_open_offline(const char *filename, unsigned int type, int *err,
              ^
pcapdj.c:430:11: error: too few arguments to function ‘wtap_open_offline’
     wth = wtap_open_offline ( filename, (int*)&err, (char**)&errinfo, FALSE);
           ^
In file included from pcapdj.c:29:0:
/usr/include/wireshark/wiretap/wtap.h:1377:14: note: declared here
 struct wtap* wtap_open_offline(const char *filename, unsigned int type, int *err,

**Comment by haegardev** [comment]
Thank you for reporting. A suggested fix is in 6add95342b856d3a9c01f215bb24878ec2d723be. Tested on Ubuntu 16.04.
